sonar.projectKey=kbeauty-shop
sonar.projectName=kbeauty-shop
sonar.sources=app,resources,routes,config,database
sonar.exclusions=**/vendor/**,**/node_modules/**,**/public/build/**,**/bootstrap/cache/**,**/storage/**,resources/js/actions/**,resources/js/routes/**,resources/js/wayfinder/**
sonar.sourceEncoding=UTF-8
